### ISSUE TITLE
Run operations on variables

### ISSUE THREAD

**Issue by Jonjoe** [jonathantneal/precss#35] opened 2015-10-08 20:53 UTC
Absolutely loving precss but i'm starting to feel a pang in my heart for variable operations.

For example
```
$gap:15px;
.somthing {
   margin:$gap/2;
}
```

or

```
$gap:15px;
$ubergap:$gap*2;
```
Couldn't find the in the docs and when i try this the css is outputted unprocessed. 

Any help? <3

**Comment by jonathantneal** [comment] 2015-10-22 02:54
PreCSS prefers explicit math. This would be a use-case for `calc`.

```css
margin: calc($gap / 2);
```

**Comment by jonathantneal** [comment] 2015-10-23 20:47
Closing as duplicate of #18

**Closed by jonathantneal** 2015-10-23 20:47 UTC
